import { describe, expect, it } from "vitest"
import type { CorpusDocument } from "@/lib/ai/corpus/types"
import { rankCandidates } from "@/lib/ai/retrieval/candidates"
import { reciprocalRankFusion, type FusedCandidate } from "@/lib/ai/retrieval/rrf"

/**
 * Candidates are generated by three retrievers whose scores are not comparable;
 * the tracker scorer is what actually decides their order, with one deliberate
 * exception.
 *
 * A fuzzy hit is a typo-tolerance hit: the query says "haibarra", the document
 * says "haibara" and scoreEntry returns 0 for it — by definition, since it
 * cannot see the greppable relationship between the two. Dropping zero scores
 * the way rankEntries does internally would delete the fuzzy branch's entire
 * output, so a zero survives, ranked below everything that scored. These tests
 * pin that rule and the determinism of the ordering around it.
 */

const lodgeDoc: CorpusDocument = {
  id: "entry:ep-004",
  source: "content_entries",
  title: "Ski Lodge Case",
  body: "A locked-room murder at a mountain lodge.",
  url: "/tracker/ep-004",
  metadata: { air_date: "1996-02-05" },
  episodeNumber: 4,
}

const twoKeywordDoc: CorpusDocument = {
  id: "entry:ep-096",
  source: "content_entries",
  title: "The Mountain Lodge Murder Case",
  body: "A blizzard traps the suspects in the lodge.",
  url: "/tracker/ep-096",
  metadata: { air_date: "1998-02-23" },
  episodeNumber: 96,
}

const numberedDoc: CorpusDocument = {
  id: "entry:ep-500",
  source: "content_entries",
  title: "The Clash of Red and Black",
  body: "A showdown with the Black Organization.",
  url: "/tracker/ep-500",
  metadata: { air_date: "2008-02-25" },
  episodeNumber: 500,
}

const haibaraDoc: CorpusDocument = {
  id: "character:ai-haibara",
  source: "characters",
  title: "Ai Haibara",
  body: "A former Black Organization chemist who also answers to Sherry.",
  url: "/characters",
  metadata: {},
  aliases: ["sherry", "shiho"],
}

const conanDoc: CorpusDocument = {
  id: "character:conan-edogawa",
  source: "characters",
  title: "Conan Edogawa",
  body: "A shrunken high-school detective living as a child.",
  url: "/characters",
  metadata: {},
  aliases: ["shinichi"],
}

/** A fused candidate with a single fts origin unless a test says otherwise. */
function fused(
  id: string,
  rrf: number,
  ranks: Record<string, number> = { fts: 1 }
): FusedCandidate {
  return { id, rrf, ranks }
}

describe("rankCandidates", () => {
  it("keeps a zero-score typo-tolerance hit after everything that scored", () => {
    // The fuzzy branch's only job: "haibarra" has to reach the Haibara document
    // even though the scorer, looking only for the literal term, cannot find
    // it there. The two character docs score 0 and stay anyway.
    const candidates = reciprocalRankFusion([
      { source: "fts", ids: ["entry:ep-004"] },
      { source: "fuzzy", ids: ["character:ai-haibara", "character:conan-edogawa"] },
    ])

    const result = rankCandidates(
      candidates,
      [lodgeDoc, haibaraDoc, conanDoc],
      ["lodge", "haibarra"]
    )

    expect(result.map((entry) => entry.doc.id)).toEqual([
      "entry:ep-004",
      "character:ai-haibara",
      "character:conan-edogawa",
    ])
    expect(result[0].score).toBeGreaterThan(0)
    expect(result[1].score).toBe(0)
    expect(result[2].score).toBe(0)

    // "After every scored doc" is the rule, not "last": the zeros must form a
    // suffix, so no zero can ever be interleaved with a scored document.
    const firstZero = result.findIndex((entry) => entry.score === 0)
    expect(result.slice(firstZero).every((entry) => entry.score === 0)).toBe(true)
  })

  it("orders the scored group by rankEntries, not by rrf", () => {
    // fts ranks the weaker document first; the scorer sees "lodge" and "murder"
    // in the other one's title and must promote it anyway.
    const candidates = [fused("entry:ep-004", 1 / 51), fused("entry:ep-096", 1 / 52)]

    const result = rankCandidates(candidates, [lodgeDoc, twoKeywordDoc], ["lodge", "murder"])

    expect(result.map((entry) => entry.doc.id)).toEqual(["entry:ep-096", "entry:ep-004"])
    expect(result[0].score).toBeGreaterThan(result[1].score)
  })

  it("promotes an exact episode number over a title-only match", () => {
    const candidates = [fused("entry:ep-004", 1 / 51), fused("entry:ep-500", 1 / 52)]

    const withNumbers = rankCandidates(candidates, [lodgeDoc, numberedDoc], ["lodge"], {
      numbers: [500],
    })
    expect(withNumbers.map((entry) => entry.doc.id)).toEqual(["entry:ep-500", "entry:ep-004"])

    // Without the option the number is invisible: the doc whose title never
    // says "lodge" scores 0 and falls to the survivor group.
    const withoutNumbers = rankCandidates(candidates, [lodgeDoc, numberedDoc], ["lodge"])
    expect(withoutNumbers.map((entry) => entry.doc.id)).toEqual(["entry:ep-004", "entry:ep-500"])
    expect(withoutNumbers[1].score).toBe(0)
  })

  it("puts the earlier entry first when preferEarliest is set", () => {
    const candidates = [fused("entry:ep-004", 1 / 51), fused("entry:ep-096", 1 / 52)]

    const byScore = rankCandidates(candidates, [lodgeDoc, twoKeywordDoc], ["lodge", "murder"])
    expect(byScore.map((entry) => entry.doc.id)).toEqual(["entry:ep-096", "entry:ep-004"])

    // A debut question is about time: the 1998 title that shouts both keywords
    // must not outrank the 1996 entry that answers it.
    const earliest = rankCandidates(candidates, [lodgeDoc, twoKeywordDoc], ["lodge", "murder"], {
      preferEarliest: true,
    })
    expect(earliest.map((entry) => entry.doc.id)).toEqual(["entry:ep-004", "entry:ep-096"])
    expect(earliest.every((entry) => entry.score > 0)).toBe(true)
  })

  it("breaks a score tie with rrf", () => {
    const tieA: CorpusDocument = {
      id: "entry:tie-a",
      source: "content_entries",
      title: "Mountain Lodge Case",
      body: "",
      url: null,
      metadata: {},
    }
    const tieB: CorpusDocument = {
      id: "entry:tie-b",
      source: "content_entries",
      title: "Mountain Lodge Case",
      body: "",
      url: null,
      metadata: {},
    }
    // Given worse-rrf-first on purpose: with identical scores and no air dates
    // rankEntries has nothing else to sort on, so only the rrf order makes the
    // output reproducible rather than dependent on the caller's array order.
    const candidates = [
      fused("entry:tie-b", 1 / 51),
      fused("entry:tie-a", 1 / 51 + 1 / 53, { fts: 3, fuzzy: 1 }),
    ]

    const result = rankCandidates(candidates, [tieA, tieB], ["lodge"])

    expect(result.map((entry) => entry.doc.id)).toEqual(["entry:tie-a", "entry:tie-b"])
  })

  it("reports every source an id was retrieved by", () => {
    const candidates = [fused("entry:ep-096", 0.03, { fts: 2, fuzzy: 1 })]

    const result = rankCandidates(candidates, [twoKeywordDoc], ["lodge"])

    expect(result[0].rrf).toBe(0.03)
    expect([...result[0].origins].sort()).toEqual(["fts", "fuzzy"])
  })

  it("ignores candidate ids the hydration step could not resolve", () => {
    const result = rankCandidates(
      [fused("entry:ep-004", 1 / 51), fused("ghost:missing", 1 / 52)],
      [lodgeDoc, haibaraDoc],
      ["lodge"]
    )

    // Candidates drive the ranking, so a hydrated doc no branch retrieved is
    // not a result, and an id with no document is skipped rather than thrown on.
    expect(result.map((entry) => entry.doc.id)).toEqual(["entry:ep-004"])
  })

  it("returns only the best document when limit is 1", () => {
    const candidates = [
      fused("entry:ep-004", 1 / 51),
      fused("entry:ep-096", 1 / 52),
      fused("character:ai-haibara", 1 / 53, { fuzzy: 1 }),
    ]

    const result = rankCandidates(
      candidates,
      [lodgeDoc, twoKeywordDoc, haibaraDoc],
      ["lodge", "murder"],
      { limit: 1 }
    )

    expect(result).toHaveLength(1)
    expect(result[0].doc.id).toBe("entry:ep-096")
  })

  it("caps the merged scored and survivor groups at the default limit of 12", () => {
    const scoredDocs: CorpusDocument[] = Array.from(
      { length: 13 },
      (_, index): CorpusDocument => ({
        id: `entry:many-${index}`,
        source: "content_entries",
        title: `Mountain Lodge Case ${index}`,
        body: "",
        url: null,
        metadata: {},
      })
    )
    const zeroDocs: CorpusDocument[] = Array.from(
      { length: 3 },
      (_, index): CorpusDocument => ({
        id: `character:quiet-${index}`,
        source: "characters",
        title: `Quiet Character ${index}`,
        body: "",
        url: null,
        metadata: {},
      })
    )
    const allDocs = [...scoredDocs, ...zeroDocs]
    const candidates = reciprocalRankFusion([
      { source: "fts", ids: allDocs.map((doc) => doc.id) },
    ])

    const result = rankCandidates(candidates, allDocs, ["lodge"])

    // Both groups are concatenated before the single truncation, so the zeros
    // fall outside the cut and 13 matching docs still return exactly the top 12.
    expect(result).toHaveLength(12)
    expect(result.every((entry) => entry.score > 0)).toBe(true)
    expect(result.map((entry) => entry.doc.id)).toEqual(
      scoredDocs.slice(0, 12).map((doc) => doc.id)
    )
  })

  it("returns [] for no candidates or for no documents", () => {
    expect(rankCandidates([], [lodgeDoc], ["lodge"])).toEqual([])
    expect(rankCandidates([fused("entry:ep-004", 1 / 51)], [], ["lodge"])).toEqual([])
  })
})
